version: "3.8"

services:
  printer3d:
    build: .
    image: patrykb/printer3d_image
    container_name: printer3d_container
    restart: always
    networks:
      - patryknetwork
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: printer_mongo
    restart: always
    networks:
      - patryknetwork
    ports:
      - "27017:27017"
    volumes:
      - db-printer:/build/libs/mongodb/data

volumes:
  db-printer:

networks:
  patryknetwork: